export class Product {
    constructor(
        public name: string,
        public description: string,
        public imgTitle: string, //? is optional properties, must go after required
        public img: any,
        public price: number,
        public id?: string //generated by firebase automatically
    ) { }
}